<section class="blog_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="blog_left_sidebar">
                    <?php
                        if (count($block->getPost()->getData()) > 0) {
                            foreach ($block->getPost()->getData() as $item) {
                           ?>
                            <article class="row blog_item">
                                <div class="col-md-3">
                                    <div class="blog_info text-right">
                                        <h4 style="color: #c5322d">Tag: </h4>
                                        <p><?php echo $block->getTag($item["post_id"]) ?>
                                        <h4 style="color: #c5322d">Category: </h4>
                                        <p><?php echo $block->getCategory($item["post_id"]) ?>
                                        <ul class="blog_meta list">
                                            <h4 style="color: #c5322d">Publish Date From: </h4>
                                            <li><?php echo $item["publish_date_from"]?><i class="lnr lnr-calendar-full"></i></li>
                                            <h4 style="color: #c5322d">Publish Date To: </h4>
                                            <li><?php echo $item["publish_date_to"] ?><i class="lnr lnr-calendar-full"></i></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-md-9">
                                    <div class="blog_post">
                                        <a href="<?php echo $block->postURL($item["post_id"]) ?>"><img src="<?php echo (!empty($item["thumbnail"]) ? $item["thumbnail"]
                                            : "http://magento2local.com/media/ngocthanh/tmp/image/default.jpg") ?>" alt=""></a>
                                        <div class="blog_details">
                                            <a href="<?php echo $block->postURL($item["post_id"]) ?>"><h2><?php echo $item["post_title"]?></h2></a>
                                            <p><?= $item["short_description"] ?></p>
                                            <a href="<?php echo $block->postURL($item["post_id"]) ?>" class="white_bg_btn">View More</a>
                                        </div>
                                    </div>
                                </div>
                            </article>
                    <?php
                            }
                        }
                    ?>
                    <?php if ($block->getPagerHtml()): ?>
                        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
                    <?php endif ?>
                </div>
            </div>
            <?php echo $block->getChildHtml("rightbar")?>
        </div>
    </div>
</section>

