<?php
    if ($block->getRelatedProduct()->getSize() > 0) {
        $count = 1;
        foreach ($block->getRelatedProduct() as $item) {
            ?>
        <div class="col-sm-3">
            <div class="card" style="width:100%">
                <img class="card-img-top" src="<?php echo $item->getThumbnail() ?>" alt="Card image">
                <div class="card-body">
                    <h4 style="text-align: center" class="card-title"><?php echo $item->getName() ?></h4>
                    <p style="color: red; text-align: center" class="card-text">Price: <?php echo $item->getPrice() ?></p>
                </div>
            </div>
        </div>
        <?php
            if ($count == 4) {
                break;
            }
            $count++;
        }
    }

?>
