<?php

namespace NgocThanh\Blog\Ui\Category\Source;

/**
 * Class DataProvider
 * @package NgocThanh\Blog\Ui\Category\Source
 */
class DataProvider extends \Magento\Ui\DataProvider\AbstractDataProvider
{
    /**
     * @var
     */
    protected $loadedData;


    public function __construct(
        $name,
        $primaryFieldName,
        $requestFieldName,
        \NgocThanh\Blog\Model\ResourceModel\Category\CollectionFactory $collectionFactory,
        array $meta = [],
        array $data = []
    ) {
        parent::__construct($name, $primaryFieldName, $requestFieldName, $meta, $data);
        $this->collection = $collectionFactory->create();
    }

    /**
     * @return array
     */
    public function getData()
    {
        return parent::getData(); // TODO: Change the autogenerated stub
    }


}
