<?php
    $post = $block->getPost()[0];
?>
<section class="blog_area single-post-area p_120">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 posts-list">
                <div class="single-post row">
                    <div class="col-lg-12">
                        <div class="feature-img">
                            <img class="img-fluid" src="<?php echo (!empty($post["thumbnail"])) ? $post["thumbnail"]
                                : "http://magento2local.com/media/ngocthanh/tmp/image/default.jpg"  ?> " alt="">
                        </div>
                    </div>
                    <div class="col-lg-3  col-md-3">
                        <div class="blog_info text-right">
                            <div class="post_tag">
                                <a href="#">Food,</a>
                                <a class="active" href="#">Technology,</a>
                                <a href="#">Politics,</a>
                                <a href="#">Lifestyle</a>
                            </div>
                            <ul class="blog_meta list">
                                <li><a href="#">Mark wiens<i class="lnr lnr-user"></i></a></li>
                                <li><a href="#"><?php echo $post["publish_date_from"] ?><i class="lnr lnr-calendar-full"></i></a></li>
                                <li><a href="#"><?php echo $post["publish_date_to"] ?><i class="lnr lnr-calendar-full"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-9 col-md-9 blog_details">
                        <h2><?php echo $post["post_title"] ?></h2>
                        <p style="margin-top: 30px" class="excert">
                            <?php echo $post["short_description"] ?>
                        </p>
                    </div>
                    <div class="col-lg-12">
                        <div class="quotes">
                            Content
                        </div>
                        <div class="row">
                            <div class="col-lg-12 mt-25">
                                <?php echo $post["content"] ?>
                            </div>
                        </div>
                    </div>
                </div>
                <h2 style="margin: 50px 0">Related Product</h2>
                <div class="row">
                    <?php echo $block->getChildHtml("slider") ?>
                </div>
            </div>
            <?php echo $block->getChildHtml("rightbar") ?>

        </div>
    </div>
</section>
<!--================Blog Area =================-->
