<?php

namespace NgocThanh\Blog\Ui\Post\Source;

class DataProvider extends \Magento\Ui\DataProvider\AbstractDataProvider
{
    public function __construct(
        $name,
        $primaryFieldName,
        $requestFieldName,
        \NgocThanh\Blog\Model\ResourceModel\Reponsitory\CollectionFactory $collectionFactory,
        array $meta = [],
        array $data = []
    ) {
        parent::__construct($name, $primaryFieldName, $requestFieldName, $meta, $data);
        $this->collection = $collectionFactory->create();
    }

    public function getData()
    {
        return parent::getData(); // TODO: Change the autogenerated stub
    }
}
